updates:
    - directory: /
      labels:
          - Dependabot
          - JavaScript
      package-ecosystem: npm
      schedule:
          interval: weekly
      versioning-strategy: increase

version: 2
